"""add severity to logs

Revision ID: fe11eded397b
Revises: 86740209ca76
Create Date: 2026-09-14 18:39:58.430315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe11eded397b'
down_revision: Union[str, Sequence[str], None] = '86740209ca76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('severity', sa.String(length=20), nullable=True))
    op.execute("UPDATE logs" \
    " SET severity = 'INFO'" \
    " WHERE severity IS NULL;")
    op.alter_column('logs', 'severity', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'severity')
    # ### end Alembic commands ###
